name: Deploy App
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Connect via SSH
    runs-on: ubuntu-latest
    steps:
    - name: Sign in to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.APP_DIR }}
          # baixar atualizacoes de codigo
          git checkout -- .
          git pull origin master
          # substituir configs para o server
          rm docker-compose.yml
          cp docker-compose-prd.yml docker-compose.yml
          # rm .env
          cp .env.prd .env
          # subir os containers
          docker-compose up -d
